services:
  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
    env_file:
      - ../.env

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    env_file:
      - ../.env
